#!/bin/sh
# # x-sweet -- sweet-expressions for x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower plus sweet,
#   with no launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# WHICH x-base, and why it is not one path.  The contract says a bundle's
# harness loads boot/x-base.x -- the launcher-free AMALGAM, which carries no
# path literals and so loads from any cwd.  That is right, and "<root>/tests/
# works in both modes" holds for the runner.  It does NOT hold for the boot
# amalgams: an install has them at share/x/boot/, a checkout builds them into
# build/boot/, and <root>/boot/ exists in neither sense in a checkout.
#
# lib/x-base.x is NOT a substitute.  It is the SOURCE entry and opens with
# (include "lib/x-core.x") -- a root-relative literal that resolves only with
# the cwd at the repo root, which is exactly the addressing failure this
# bundle exists to not repeat.  Loading it from here fails with a bare
# "include: cannot open".
#
# So: probe, install layout first.  Reported upstream; collapse to one path
# if the layouts converge.
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-sweet: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-base.x and build/boot/x-base.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# Three things here are not obvious, and each costs an afternoon:
#
# 1. %install-root FIRST.  An amalgam carries no include literals, but its
#    deferred `import` forms resolve against the installed tree as it boots,
#    and module.x learns where that is from %install-root.  x.sh emits this
#    same line ahead of every boot entry; a harness loading an amalgam
#    directly has to emit it too.
#
# 2. boot/x-base.x, NOT a dialect entry.  he.x / xe.x / rn.x end with
#    (unless %batch? (do (%banner) (repl))) and would start a REPL underneath
#    the suite.  x-base.x is the launcher-free one, and being an amalgam it
#    carries no path literals, so it loads from any cwd.
#
# 3. NEVER re-include a platform module the tower already has.  The 2024
#    sweet-base.x opened with (include "lib/x-core.x"); on top of a booted
#    tower that is a SEGFAULT with no diagnostic, not an error.  Deleting
#    that one line is what took this suite from dead to 68/72.  run.x owns
#    the boot; nothing under sweet/ includes anything from the platform.
#
# The bundle root is armed the same way run.x arms it, so `import sweet/base`
# resolves here exactly as it does at the prompt.
cat > "$OUT" <<EOF
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
(import-path! "$BUNDLE")
(import sweet/base)
(set! %repl-print %sweet-repl-print)
; SHIM FOR THE RUNNER, not for the language.  Direct mode emits (heap-collect)
; between snippets as its OOM guard, but that bare global was renamed to the
; Heap class and the awk was never updated -- so the branch written for this
; personality raises "Unbound SYMBOL heap-collect" on every snippet boundary.
; Reported upstream; delete this line when the runner says (Heap collect).
(def heap-collect (fn (_) (Heap collect)))
; ARMED LAST, and nothing may follow it but the loop.  Registering SWEET-WS
; changes how the very next character of input is tokenized -- including the
; rest of this file.  Every form above is ordinary x read by ordinary rules;
; the spec text the runner appends after this is the first thing read as sweet.
(%sweet-arm!)

; THE LOOP LIVES HERE, IN THE HARNESS, because the runner is in direct mode
; (REPL_CMD=" ").  Direct mode exists for exactly this personality -- the
; platform's own awk says so: "Used by Sweet where indentation-based grouping
; must see raw newlines/tokens."  It skips the %T harness AND the (begin ...)
; wrapper the standard mode puts around every snippet, and the wrapper is the
; part that matters: parentheses override indentation in SRFI-110, so
;
;   (begin define x
;     42
;   )
;
; is one flat call, not a definition with a child.  Wrapped, every indentation
; spec in this bundle reads as something it does not mean.
;
; The cost of direct mode is that nothing supplies a read-eval-print loop, so
; the harness must call one.  %sweet-run comes from sweet/base.x, DEFINED
; before the arm and merely CALLED after it -- see the note there: a multi-line
; form read after arming has whitespace sentinels injected into it, which is
; silent and fatal in an arity-sensitive form like "if".  Nothing below this
; line may span two lines.
(%sweet-run)
EOF
