#!/bin/sh
# # x-sweet -- the Sweet lang for x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower plus Sweet,
#   with no launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# The launcher-free boot amalgam carries no path literals and loads from any
# cwd, but lives at share/x/boot/ when installed and build/boot/ in a checkout,
# so probe both, install layout first. lib/x-base.x is not a substitute: it is
# the source entry and opens with a root-relative (include "lib/x-core.x")
# that resolves only from the repo root.
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-sweet: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-base.x and build/boot/x-base.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# Three requirements on the generated file:
#
# 1. %install-root first. An amalgam carries no include literals, but its
#    deferred `import` forms resolve against the installed tree, which module.x
#    locates from %install-root. x.sh emits the same line ahead of every boot
#    entry.
#
# 2. boot/x-base.x, not a dialect entry. he.x / xe.x / rn.x end by starting a
#    REPL, which would run underneath the suite. x-base.x is launcher-free.
#
# 3. Never re-include a platform module the booted tower already has; on top
#    of a booted tower that segfaults with no diagnostic. run.x owns the boot,
#    and nothing under sweet/ includes anything from the platform.
#
# The bundle root is armed the same way run.x arms it, so `import sweet/base`
# resolves here as it does at the prompt.
cat > "$OUT" <<EOF
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
(import-path! "$BUNDLE")
(import sweet/base)
(set! %repl-print %sweet-repl-print)
; Shim for the runner: direct mode emits (heap-collect) between snippets, but
; that global moved onto the Heap class. x-lang#523; delete this line when the
; runner says (Heap collect).
(def heap-collect (fn (_) (Heap collect)))
; Arm last, and nothing multi-line may follow: registering SWEET-WS changes how
; the next character is tokenized. Go through `repl` so a state image of this
; harness can start it again; the arm stays inside it, the last thing before
; the stream is read.
(set! repl (fn (_) (%seq (%sweet-arm!) (%sweet-run))))
; Not while the image is being written: that child's stdin is the writer's own
; script, which %sweet-run would read as sweet source. %image-writing is bound
; in that child alone; a normal boot raises Unbound and answers #f.
(if (guard (_ #f) %image-writing) () (repl))
EOF
